<a href="https://colab.research.google.com/github/udayanjansai/ML_For_Autism_Detection/blob/main/ASD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
child = pd.read_csv("/content/drive/MyDrive/datasets/Autism_Child_Data.csv")
adult = pd.read_csv("/content/drive/MyDrive/datasets/Autism_Adult_Data.csv")
adolescent = pd.read_csv("/content/drive/MyDrive/datasets/Autism_Adolescent_Data.csv")
screening = pd.read_csv("/content/drive/MyDrive/datasets/Toddler Autism dataset July 2018.csv")

In [ ]:
print("Child:", child.columns.tolist())
print("Adult:", adult.columns.tolist())
print("Adolescent:", adolescent.columns.tolist())
print("Screening:", screening.columns.tolist())


Child: ['id', 'A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score', 'A6_Score', 'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'age', 'gender', 'ethnicity', 'jundice', 'austim', 'contry_of_res', 'used_app_before', 'result', 'age_desc', 'relation', 'Class/ASD']
Adult: ['id', 'A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score', 'A6_Score', 'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'age', 'gender', 'ethnicity', 'jundice', 'austim', 'contry_of_res', 'used_app_before', 'result', 'age_desc', 'relation', 'Class/ASD']
Adolescent: ['id', 'A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score', 'A6_Score', 'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'age', 'gender', 'ethnicity', 'jundice', 'austim', 'contry_of_res', 'used_app_before', 'result', 'age_desc', 'relation', 'Class/ASD']
Screening: ['Case_No', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Age_Mons', 'Qchat-10-Score', 'Sex', 'Ethnicity', 'Jaundice', 'Family_mem_with_ASD', 'Who completed the 

In [ ]:
print("Child dataset:", child.shape)
print("Adult dataset:", adult.shape)
print("Adolescent dataset:", adolescent.shape)
print("Screening dataset:", screening.shape)

Child dataset: (292, 22)
Adult dataset: (704, 22)
Adolescent dataset: (104, 22)
Screening dataset: (1054, 19)


In [ ]:
print("Child dataset:", child['Class/ASD'].value_counts())
print("Adult dataset:", adult['Class/ASD'].value_counts())
print("Adolescent dataset:", adolescent['Class/ASD'].value_counts())
print("Screening dataset:", screening['Class/ASD Traits '].value_counts())

Child dataset: Class/ASD
NO     151
YES    141
Name: count, dtype: int64
Adult dataset: Class/ASD
NO     515
YES    189
Name: count, dtype: int64
Adolescent dataset: Class/ASD
YES    63
NO     41
Name: count, dtype: int64
Screening dataset: Class/ASD Traits 
Yes    728
No     326
Name: count, dtype: int64


In [ ]:
screening.rename(columns={
    'A1': 'A1_Score',
    'A2': 'A2_Score',
    'A3': 'A3_Score',
    'A4': 'A4_Score',
    'A5': 'A5_Score',
    'A6': 'A6_Score',
    'A7': 'A7_Score',
    'A8': 'A8_Score',
    'A9': 'A9_Score',
    'A10': 'A10_Score',
    'Sex': 'gender',
    'Ethnicity': 'ethnicity',
    'Jaundice': 'jundice',
    'Family_mem_with_ASD': 'austim',
    'Class/ASD Traits ': 'Class/ASD'
}, inplace=True)


In [ ]:
screening["age"] = screening["Age_Mons"] / 12

In [ ]:
selected_cols = [
    'A1_Score','A2_Score','A3_Score','A4_Score','A5_Score',
    'A6_Score','A7_Score','A8_Score','A9_Score','A10_Score',
    'age','gender','ethnicity','jundice','austim',
    'Class/ASD'
]

In [ ]:
child = child[selected_cols]
adult = adult[selected_cols]
adolescent = adolescent[selected_cols]
screening = screening[selected_cols]

In [ ]:

print("Child:", child.shape)
print("Adult:", adult.shape)
print("Adolescent:", adolescent.shape)
print("Screening:", screening.shape)

Child: (292, 16)
Adult: (704, 16)
Adolescent: (104, 16)
Screening: (1054, 16)


In [ ]:

child['source'] = 'child'
adult['source'] = 'adult'
adolescent['source'] = 'adolescent'
screening['source'] = 'screening'

combined = pd.concat([child, adult, adolescent, screening], ignore_index=True)
df = combined

In [ ]:
# from sklearn.utils import resample
# target_size = 500

# child_bal = resample(child, replace=True, n_samples=target_size, random_state=42)
# adult_bal = resample(adult, replace=True, n_samples=target_size, random_state=42)
# adolescent_bal = resample(adolescent, replace=True, n_samples=target_size, random_state=42)
# screening_bal = resample(screening, replace=True, n_samples=target_size, random_state=42)

# combined = pd.concat(
#     [child_bal, adult_bal, adolescent_bal, screening_bal],
#     ignore_index=True
# )

In [ ]:
df=combined
print("\nShape:")
print(df.shape)


Shape:
(2154, 17)


In [ ]:
print("\nMissing values:")
print(df.isnull().sum())


Missing values:
A1_Score     0
A2_Score     0
A3_Score     0
A4_Score     0
A5_Score     0
A6_Score     0
A7_Score     0
A8_Score     0
A9_Score     0
A10_Score    0
age          0
gender       0
ethnicity    0
jundice      0
austim       0
Class/ASD    0
source       0
dtype: int64


In [ ]:
print("\nTarget distribution:")
print(df["Class/ASD"].value_counts())


Target distribution:
Class/ASD
Yes    728
NO     707
YES    393
No     326
Name: count, dtype: int64


In [ ]:
import pandas as pd


print("Before cleaning:")
print(df["Class/ASD"].value_counts())

df["Class/ASD"] = (
    df["Class/ASD"]
    .astype(str)
    .str.strip()
    .str.upper()
)

print("\nAfter fixing target labels:")
print(df["Class/ASD"].value_counts())

df["ethnicity"] = df["ethnicity"].replace("?", pd.NA)
df["ethnicity"]=df["ethnicity"].fillna(df["ethnicity"].mode()[0])

for col in ["gender", "jundice", "austim"]:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()




Before cleaning:
Class/ASD
Yes    728
NO     707
YES    393
No     326
Name: count, dtype: int64

After fixing target labels:
Class/ASD
YES    1121
NO     1033
Name: count, dtype: int64


In [ ]:
count_q = (df["age"] == "?").sum()
print("Number of '?' in age:", count_q)
print("Total rows:", len(df))
print("Percentage:", (count_q / len(df)) * 100)

Number of '?' in age: 6
Total rows: 2154
Percentage: 0.2785515320334262


In [ ]:
df = df[df["age"] != "?"]
df.loc[:, "age"] = pd.to_numeric(df["age"])

print("Rows after removal:", df.shape)


Rows after removal: (2148, 17)


In [ ]:
from sklearn.preprocessing import LabelEncoder

categorical_cols = df.select_dtypes(include="object").columns
label_encoders = {}

for col in categorical_cols:
    if col != "Class/ASD" and col !="source":
        le = LabelEncoder()
        df.loc[:, col] = le.fit_transform(df[col])
        label_encoders[col] = le

In [ ]:
df.head()

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,gender,ethnicity,jundice,austim,Class/ASD,source
0,1,1,0,0,1,1,0,1,0,0,27,1,6,0,0,NO,child
1,1,1,0,0,1,1,0,1,0,0,27,1,4,0,0,NO,child
2,1,1,0,0,0,1,1,1,0,0,27,1,12,0,0,NO,child
3,0,1,0,0,1,1,0,0,0,1,26,0,12,1,0,NO,child
4,1,1,1,1,1,1,1,1,1,1,26,1,6,1,0,YES,child


In [ ]:
df.loc[:, "Class/ASD"] = df["Class/ASD"].map({"NO": 0, "YES": 1})

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.utils import resample

# Step 3: Split first on original data
X = df.drop("Class/ASD", axis=1)
y = df["Class/ASD"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Step 4: Resample each source group within training set only
train_df = X_train.copy()
train_df['Class/ASD'] = y_train

resampled_groups = []
for source in ['child', 'adult', 'adolescent', 'screening']:
    group = train_df[train_df['source'] == source]
    group_resampled = resample(group, replace=True, n_samples=500, random_state=42)
    resampled_groups.append(group_resampled)

train_resampled = pd.concat(resampled_groups, ignore_index=True)

# Step 5: Separate X_train and y_train after resampling
X_train = train_resampled.drop(['Class/ASD', 'source'], axis=1)
y_train = train_resampled['Class/ASD']

# Drop source from test set too
X_test = X_test.drop('source', axis=1)

In [ ]:
print(train_resampled['source'].value_counts())
print("Total training rows:", len(train_resampled))
print("Test rows:", len(X_test))

source
child         500
adult         500
adolescent    500
screening     500
Name: count, dtype: int64
Total training rows: 2000
Test rows: 430


In [ ]:
X_train = X_train.apply(pd.to_numeric, errors='coerce')
X_test = X_test.apply(pd.to_numeric, errors='coerce')

# verify
print(X_train.dtypes)
print(X_train.isnull().sum())  # check if any NaN appeared after conversion

A1_Score     int64
A2_Score     int64
A3_Score     int64
A4_Score     int64
A5_Score     int64
A6_Score     int64
A7_Score     int64
A8_Score     int64
A9_Score     int64
A10_Score    int64
age          int64
gender       int64
ethnicity    int64
jundice      int64
austim       int64
dtype: object
A1_Score     0
A2_Score     0
A3_Score     0
A4_Score     0
A5_Score     0
A6_Score     0
A7_Score     0
A8_Score     0
A9_Score     0
A10_Score    0
age          0
gender       0
ethnicity    0
jundice      0
austim       0
dtype: int64


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

# Convert y_train and y_test to integer type
y_train = y_train.astype(int)
y_test = y_test.astype(int)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Random Forest Accuracy: 0.9302325581395349
[[189  17]
 [ 13 211]]
              precision    recall  f1-score   support

           0       0.94      0.92      0.93       206
           1       0.93      0.94      0.93       224

    accuracy                           0.93       430
   macro avg       0.93      0.93      0.93       430
weighted avg       0.93      0.93      0.93       430



In [ ]:
from sklearn.model_selection import cross_val_score
import numpy as np

scores = cross_val_score(rf, X_train, y_train, cv=5)

print("CV Scores:", scores)
print("Mean CV Accuracy:", np.mean(scores))


CV Scores: [0.9325 0.855  0.995  0.955  0.6175]
Mean CV Accuracy: 0.8710000000000001


In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
import numpy as np

# Initialize model
et = ExtraTreesClassifier(
    n_estimators=200,
    random_state=42
)

# Train
et.fit(X_train, y_train)

# Predict
y_pred = et.predict(X_test)

print("=== Extra Trees Results ===")
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Cross-validation
cv_scores = cross_val_score(et, X_train, y_train, cv=5)

print("\nCV Scores:", cv_scores)
print("Mean CV Accuracy:", np.mean(cv_scores))


=== Extra Trees Results ===
Test Accuracy: 0.9162790697674419

Confusion Matrix:
[[187  19]
 [ 17 207]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.91      0.91       206
           1       0.92      0.92      0.92       224

    accuracy                           0.92       430
   macro avg       0.92      0.92      0.92       430
weighted avg       0.92      0.92      0.92       430


CV Scores: [0.8925 0.9475 0.9875 0.9425 0.9125]
Mean CV Accuracy: 0.9364999999999999


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

rf = RandomForestClassifier(random_state=42)

grid = GridSearchCV(
    rf,
    param_grid,
    cv=5,
    n_jobs=-1,
    verbose=1
)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)


Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300}
Best CV Score: 0.8780000000000001


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
import numpy as np

ada = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=200,
    learning_rate=0.5,
    random_state=42
)

ada.fit(X_train, y_train)

y_pred = ada.predict(X_test)

print("=== AdaBoost Results ===")
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Cross-validation
cv_scores = cross_val_score(ada, X_train, y_train, cv=5)

print("\nCV Scores:", cv_scores)
print("Mean CV Accuracy:", np.mean(cv_scores))


=== AdaBoost Results ===
Test Accuracy: 1.0

Confusion Matrix:
[[206   0]
 [  0 224]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       206
           1       1.00      1.00      1.00       224

    accuracy                           1.00       430
   macro avg       1.00      1.00      1.00       430
weighted avg       1.00      1.00      1.00       430


CV Scores: [1.     0.93   1.     1.     0.9575]
Mean CV Accuracy: 0.9775


In [ ]:
print(X_train['age'].unique()[:10])
print(X_train['gender'].unique())

[28 30 29 25 26 32 27 31 82 43]
[0 1]


In [ ]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

param_grid_xgb = {
    "n_estimators": [100, 200, 300],
    "max_depth": [2, 3, 4],
    "learning_rate": [0.05, 0.1, 0.2],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0]
}

xgb = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

grid_xgb = GridSearchCV(
    xgb,
    param_grid_xgb,
    cv=5,
    n_jobs=-1,
    verbose=1
)

grid_xgb.fit(X_train, y_train)

print("Best Parameters (XGBoost):", grid_xgb.best_params_)
print("Best CV Score (XGBoost):", grid_xgb.best_score_)

# Evaluate best model
best_xgb = grid_xgb.best_estimator_
y_pred_xgb = best_xgb.predict(X_test)

print("\n=== Tuned XGBoost Results ===")
print("Test Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

cv_scores_xgb = cross_val_score(best_xgb, X_train, y_train, cv=5)
print("\nCV Scores:", cv_scores_xgb)
print("Mean CV Accuracy:", np.mean(cv_scores_xgb))

Fitting 5 folds for each of 243 candidates, totalling 1215 fits
Best Parameters (XGBoost): {'colsample_bytree': 0.8, 'learning_rate': 0.2, 'max_depth': 2, 'n_estimators': 300, 'subsample': 0.7}
Best CV Score (XGBoost): 0.9700000000000001

=== Tuned XGBoost Results ===
Test Accuracy: 0.986046511627907

Confusion Matrix:
[[202   4]
 [  2 222]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       206
           1       0.98      0.99      0.99       224

    accuracy                           0.99       430
   macro avg       0.99      0.99      0.99       430
weighted avg       0.99      0.99      0.99       430


CV Scores: [0.995  0.9575 1.     0.9925 0.905 ]
Mean CV Accuracy: 0.9700000000000001


In [ ]:
import lightgbm as lgb
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

param_grid_lgbm = {
    "n_estimators": [100, 200, 300],
    "max_depth": [2, 3, 4],
    "learning_rate": [0.05, 0.1, 0.2],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0]
}

lgbm = lgb.LGBMClassifier(
    random_state=42,
    verbose=-1
)

grid_lgbm = GridSearchCV(
    lgbm,
    param_grid_lgbm,
    cv=5,
    n_jobs=-1,
    verbose=1
)

grid_lgbm.fit(X_train, y_train)

print("Best Parameters (LightGBM):", grid_lgbm.best_params_)
print("Best CV Score (LightGBM):", grid_lgbm.best_score_)

# Evaluate best model
best_lgbm = grid_lgbm.best_estimator_
y_pred_lgbm = best_lgbm.predict(X_test)

print("\n=== Tuned LightGBM Results ===")
print("Test Accuracy:", accuracy_score(y_test, y_pred_lgbm))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_lgbm))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_lgbm))

cv_scores_lgbm = cross_val_score(best_lgbm, X_train, y_train, cv=5)
print("\nCV Scores:", cv_scores_lgbm)
print("Mean CV Accuracy:", np.mean(cv_scores_lgbm))

Fitting 5 folds for each of 243 candidates, totalling 1215 fits
Best Parameters (LightGBM): {'colsample_bytree': 0.7, 'learning_rate': 0.2, 'max_depth': 2, 'n_estimators': 300, 'subsample': 0.7}
Best CV Score (LightGBM): 0.9334999999999999

=== Tuned LightGBM Results ===
Test Accuracy: 0.9837209302325581

Confusion Matrix:
[[202   4]
 [  3 221]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.98       206
           1       0.98      0.99      0.98       224

    accuracy                           0.98       430
   macro avg       0.98      0.98      0.98       430
weighted avg       0.98      0.98      0.98       430


CV Scores: [0.98   0.92   1.     0.99   0.7775]
Mean CV Accuracy: 0.9334999999999999
